name: github-pr-release

on:
  push:
    branches:
    - 'y7g/github-pr-release/**'
  pull_request:
    paths:
      - .github/workflows/github-pr-release.yml
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
  github-pr-release-staging:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: yutailang0119/action-github-pr-release@v3.0.0
        with:
          token: ${{ github.token }}
          production_branch: y7g/github-pr-release/production
          staging_branch: y7g/github-pr-release/staging
          label: y7g/action-github-pr-release
  github-pr-release-empty:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: yutailang0119/action-github-pr-release@v3.0.0
        with:
          token: ${{ github.token }}
          production_branch: y7g/github-pr-release/production
          staging_branch: y7g/github-pr-release/empty
          dry_run: true

